
# Database Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/users
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#logging.level.org.springframework=DEBUG
logging.level.org.springframework.boot.autoconfigure=ERROR
logging.level.org.hibernate.orm.connections.pooling=ERROR
logging.level.com.zaxxer.hikari=DEBUG

spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.max-lifetime=1800000